#!/usr/bin/env bash
clear

docker rmi $(docker images -q)
docker rm -v $(docker ps -qa)

rm -rf /home/fte
mkdir -p /home/fte
chown -R 755 /home/fte
docker rm -f fte

docker build \
  --no-cache \
  --pull \
  -t b14ckp4nd\docker-fte:latest . && \
  docker create \
  --name=fte \
  --cap-add=NET_ADMIN \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Berlin \
  -e port=443 \
  -e PROXY_IP=google.com \
  -e PROXY_PORT=80 \
  -e INTERFACE=eth0 \
  -p 443:443 \
  -v /home/fte:/config \
  --restart unless-stopped \
  b14ckp4nd\docker-fte:latest && \
  docker start fte && \
   docker logs fte -f